### PR TITLE
Add tests to cover some part of actionsmap.py

### PR DESCRIPTION
**Pull request by decentral1se**
Linking to https://github.com/YunoHost/issues/issues/1255 and https://github.com/YunoHost/issues/issues/1367.

### CODE REVIEW

**Comment by decentral1se** [comment]
OK, this is officially "better than nothing" and I think can be reviewed/merged.

**Comment by decentral1se** [comment]
I've taken a pass now and resolved comments that I dealt with.

> Something that is missing is some test tooling around msignals and m18n to test the __call__ methods of the various classes. Maybe it already exists and I'm not aware of it.

Yes, you're right. I didn't write tests against this as I got tired of it for now.

**Comment by Timost** [comment]
Ok thank you ! LGTM. Writing tests isn't the funniest part indeed.

**Comment by decentral1se** [comment]
:rocket: 

I'll merge this tomorrow or so if there are no objections.

**Pull request merged**
