### PR TITLE
Make exception more useful folder

### PR DESCRIPTION
**Pull request by Psycojoker**
Same than https://github.com/YunoHost/moulinette/pull/123 but for folder_not_exists, except we never seems to use this exception according to grep.

### CODE REVIEW

**Comment by jeromelebleu** [comment]
I'll reject your PR, sorry about that. Translations must be updated in Weblate only to avoid conflicts...

**Comment by Psycojoker** [comment]
Could you inform me on how to do that?

**Comment by jeromelebleu** [comment]
You have to log in [Weblate](https://translate.yunohost.org), select the right project and component - e.g. YunoHost / moulinette, select the English and French languages and modify the relevant key.

**Comment by jeromelebleu** [comment]
For example, here is what you have to modify for *file_not_exist* in English: https://translate.yunohost.org/translate/yunohost/moulinette/en/?q=file_not_exist&search=substring&context=on&type=all&ignored=False.

**Pull request closed without merging**
