### PR TITLE
Test the documentation under Tox

### PR DESCRIPTION
**Pull request by decentral1se**
Something to alongside https://github.com/YunoHost/moulinette/pull/213.

This should fail, then I'll fix the issues ...

### CODE REVIEW

**Comment by decentral1se** [comment]
Annnnnnndd we're done https://travis-ci.org/YunoHost/moulinette/jobs/567589419.

**Comment by Psycojoker** [comment]
Merged by hand (with an amend), thx <3

**Comment by decentral1se** [comment]
Ah, small one, should it not also be:

```diff
diff --git a/tox.ini b/tox.ini
index d76628e..895a8f0 100644
--- a/tox.ini
+++ b/tox.ini
@@ -28,7 +28,4 @@ usedevelop = False
 usedevelop = True
 commands = python -m sphinx -W doc/ doc/_build
 deps =
-  sphinx
-  mock
-  gnupg
   -r{toxinidir}/doc/requirements.txt
```

**Comment by Psycojoker** [comment]
Ah, possibly, kept your code by default.

Will try and update if it works like in your diff.

**Pull request closed without merging**
