### PR TITLE
Use Black in Moulinette

### PR DESCRIPTION
**Pull request by decentral1se**
Because manually formatting things sucks.

> https://github.com/psf/black

This will probably conflict with every other PR :cloud:

To run it, you need a Python 3 installed (see included docs) and then just run:

```
$ tox -e format  # have black format things
$ tox -e format-check  # only check if source needs formatting
```

If this is well received, we can think about it over at at [yunohost/yunohost](https://github.com/yunohost/yunohost). This comes after some discussion over at https://github.com/YunoHost/yunohost/pull/787.

### CODE REVIEW

**Comment by Psycojoker** [comment]
> This will probably conflict with every other PR cloud

Except if we run it on other PRs?

**Comment by Psycojoker** [comment]
We should probably put some stuff in place to automatically run black on every code merge also.

**Comment by decentral1se** [comment]
> This will probably conflict with every other PR cloud
>> Except if we run it on other PRs?

Yep, but I always prefer to not make conflicts for others ;) But running `tox -e format` isn't bad.

> We should probably put some stuff in place to automatically run black on every code merge also.

Travis CI will run on every PR and every merge into the stretch-unstable branch. Do you mean to run Black and have it format the source and then commit it? That sounds nice but like I saw in https://github.com/YunoHost/moulinette/pull/220/commits/7295e30ff558f653631e8e6422596b0cc88784fc, it still needs some supervision.

**Comment by decentral1se** [comment]
What do you think @Psycojoker, shall we merge or leave it for now?

**Comment by alexAubin** [comment]
Ugh if we could merge https://github.com/YunoHost/moulinette/pull/216 first that would help to not have a shitload of conflicts to handle :s

**Comment by decentral1se** [comment]
> Ugh if we could merge #216 first that would help to not have a shitload of conflicts to handle :s

Sure thing, I'll wait until then :+1:

**Comment by Psycojoker** [comment]
> Ugh if we could merge #216 first that would help to not have a shitload of conflicts to handle :s

I'm really wondering if just applying black on #216 wouldn't just solve all conflicts tbh

**Comment by Psycojoker** [comment]
(but that needs to be tested but that would really solve problems)

**Comment by decentral1se** [comment]
I'm not gonna follow this up, feel free to do it anyone else!

**Comment by alexAubin** [comment]
@decentral1se : following the merge of https://github.com/YunoHost/moulinette/pull/216 , I pushed https://github.com/YunoHost/moulinette/compare/581275aeedbc...54b8cab13375 reusing your work (I flagged you as author of the commits if that's okay)

**Pull request closed without merging**
